### ISSUE TITLE
데이터베이스 (MySQL, H2)

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/spring-study#10]
#### Task
- [ ] 데이터베이스 아키텍쳐 설계 (MySQL, H2)
- [ ] 개발 환경에 데이터베이스 연동
- [ ] 데이터베이스 Auditing
- [ ] DDL / DTO
- [ ] Repository
- [ ] CRUD 테스트
- [ ] mocker를 이용한 테스트 더미 데이터 생성

TODO: 용어와 플로우에 대한 명확한 정리가 필요

##### Q&A
- Auto-Wiring
- JPA / Hibernate
